Config = Config or {}

Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1_uaF1AVryvTiQA2g9VJKTHAK_wJOJXIJImpY69VF4s4/edit?usp=sharing',
    ['ambulance'] = '',
    ['bcso'] = 'https://docs.google.com/spreadsheets/d/1_uaF1AVryvTiQA2g9VJKTHAK_wJOJXIJImpY69VF4s4/edit?usp=sharing',
    ['doj'] = 'https://docs.google.com/spreadsheets/d/1_uaF1AVryvTiQA2g9VJKTHAK_wJOJXIJImpY69VF4s4/edit?usp=sharing',
}

Config.OnlyShowOnDuty = true

Config.Fuel = "LegacyFuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'Jarayeme Alayhe Afrad',
    [2] = 'Jarayem Marbot Be Serghatha',
    [3] = 'Jarayem Marbot Be Kolah bardari',
    [4] = 'Jarayem Asib resani Be Amval Omomi',
    [5] = 'Jarayem Alayhe Hokomat',
    [6] = 'Jarayem Alayhe Nazm',
    [7] = 'Jarayem Marbot be Salamat Va akhlagh',
    [8] = 'Jarayem Marbot be Amniyat Omomi',
    [9] = 'Jarayem Marbot be Khodro',
    [10] = 'Jarayem Marbot be Hayat Vahsh',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Simple Assault', class = 'Misdemeanor', id = 'P.C. 1001', months = 7, fine = 500, color = 'green'},
        [2] = {title = 'Adam Robaei', class = 'Misdemeanor', id = 'P.C. 1001', months = 30, fine = 1500, color = 'green'},
        [3] = {title = 'Roboodan Karmand Dolat', class = 'Misdemeanor', id = 'P.C. 1001', months = 0, fine = 0, color = 'green'},
        [4] = {title = 'Ghatl Amm', class = 'Misdemeanor', id = 'P.C. 1001', months = 100, fine = 10000, color = 'green'},
        [5] = {title = 'Ghatle Daraje 2', class = 'Misdemeanor', id = 'P.C. 1001', months = 80, fine = 8000, color = 'green'},
        [6] = {title = 'Ghatle Daraje 1', class = 'Misdemeanor', id = 'P.C. 1001', months = 400, fine = 15000, color = 'green'},
        [7] = {title = 'Tahdid Fard', class = 'Misdemeanor', id = 'P.C. 1001', months = 10, fine = 500, color = 'green'},
        [8] = {title = 'Ghatle Karmand Dolati', class = 'Misdemeanor', id = 'P.C. 1001', months = 0, fine = 0, color = 'green'},
        [9] = {title = 'Be Khatar Andakhtan Jane Digaran', class = 'Misdemeanor', id = 'P.C. 1001', months = 10, fine = 500, color = 'green'},
        [10] = {title = 'Tahdid Fardi Ba Aslahe', class = 'Misdemeanor', id = 'P.C. 1001', months = 0, fine = 5000, color = 'green'},

    },
    [2] = {
        [1] = {title = 'Petty Theft', class = 'Infraction', id = 'P.C. 2001', months = 0, fine = 250, color = 'green'},
        [2] = {title = 'Shop Robbery', class = 'Infraction', id = 'P.C. 2001', months = 15, fine = 500, color = 'green'},
        [3] = {title = 'Vehicle theft', class = 'Infraction', id = 'P.C. 2001', months = 5, fine = 250, color = 'green'},
        [4] = {title = 'Grand Thef Auto', class = 'Infraction', id = 'P.C. 2001', months = 15, fine = 500, color = 'green'},
        [5] = {title = 'Bank Robbery', class = 'Infraction', id = 'P.C. 2001', months = 60, fine = 2000, color = 'green'},
        [6] = {title = 'Javaheri', class = 'Infraction', id = 'P.C. 2001', months = 70, fine = 1250, color = 'green'},
        [7] = {title = 'Dashtan Citizen Card Serghati', class = 'Infraction', id = 'P.C. 2001', months = 10, fine = 500, color = 'green'},
        [8] = {title = 'Bank Markazi', class = 'Infraction', id = 'P.C. 2001', months = 200, fine = 8000, color = 'green'},
        [9] = {title = 'Dashtan Poole Kasif Bain 1 Ta 40 Ta', class = 'Infraction', id = 'P.C. 2001', months = 10, fine = 700, color = 'green'},
        [10] = {title = 'Dashtan Poole Kasif 40 Ta Be Bala', class = 'Infraction', id = 'P.C. 2001', months = 20, fine = 1400, color = 'green'},
       
    },
    [3] = {
        [1] = {title = 'Impersonating', class = 'Misdemeanor', id = 'P.C. 3001', months = 15, fine = 1250, color = 'green'},
        [2] = {title = 'Baj Gereftan', class = 'Misdemeanor', id = 'P.C. 3001', months = 10, fine = 2000, color = 'green'},
        [3] = {title = 'Kollah Bardari', class = 'Misdemeanor', id = 'P.C. 3001', months = 15, fine = 2500, color = 'green'},
        [4] = {title = 'Jaale Hoviat Yek Citizen', class = 'Misdemeanor', id = 'P.C. 3001', months = 0, fine = 0, color = 'green'},
        [5] = {title = 'Jaale Hovviate Yek Karmandane Dolat', class = 'Misdemeanor', id = 'P.C. 3001', months = 0, fine = 0, color = 'green'},
        [6] = {title = 'Pelak Taghallobi', class = 'Misdemeanor', id = 'P.C. 3001', months = 15, fine = 200, color = 'green'},
        [7] = {title = 'Pool Shooei', class = 'Misdemeanor', id = 'P.C. 3001', months = 40, fine = 2000, color = 'green'},
       
    },
    [4] = {
        -- [1] = {title = 'Trespassing', class = 'Misdemeanor', id = 'P.C. 4001', months = 10, fine = 450, color = 'green'},
        
    },
    [5] = {
        -- [1] = {title = 'Bribery of a Government Official', class = 'Felony', id = 'P.C. 5001', months = 20, fine = 3500, color = 'green'},
        
    },
    [6] = {
        [1] = {title = 'Disobeying a Peace Officer', class = 'infraction', id = 'P.C. 6001', months = 0, fine = 750, color = 'green'},
        [2] = {title = 'Sarpichi As Dastoor Karmand Dolat', class = 'infraction', id = 'P.C. 6001', months = 5, fine = 200, color = 'green'},
        [3] = {title = 'Ashoobgari', class = 'infraction', id = 'P.C. 6001', months = 15, fine = 500, color = 'green'},
        [4] = {title = 'Kharabkari', class = 'infraction', id = 'P.C. 6001', months = 0, fine = 500, color = 'green'},
        [5] = {title = 'Barham Zadan Aramesh', class = 'infraction', id = 'P.C. 6001', months = 5, fine = 500, color = 'green'},
        [6] = {title = 'Azar Va Azziat', class = 'infraction', id = 'P.C. 6001', months = 5, fine = 250, color = 'green'},
        [7] = {title = 'Shooresh', class = 'infraction', id = 'P.C. 6001', months = 0, fine = 0, color = 'green'},
        [8] = {title = 'Takhribe Amvale Omoomi', class = 'infraction', id = 'P.C. 6001', months = 10, fine = 0, color = 'green'},

        
    },
    [7] = {
        [1] = {title = 'Misdemeanor Possession of Marijuana', class = 'Mask', id = 'P.C. 7001', months = 5, fine = 250, color = 'green'},
        [2] = {title = 'Hamle Mavad (Daraje 3)', class = 'Mask', id = 'P.C. 7001', months = 10, fine = 1000, color = 'green'},
        [3] = {title = 'Hame Mavad (Daraje 2)', class = 'Mask', id = 'P.C. 7001', months = 40, fine = 6000, color = 'green'},
        [4] = {title = 'Hame Mavad ( Daraje 1)', class = 'Mask', id = 'P.C. 7001', months = 0, fine = 0, color = 'green'},
        [5] = {title = 'Foroosh Mavad Mokhadder', class = 'Mask', id = 'P.C. 7001', months = 30, fine = 4000, color = 'green'},
        [6] = {title = 'Kasht Marijuana', class = 'Mask', id = 'P.C. 7001', months = 0, fine = 0, color = 'green'},
        [7] = {title = 'Ghachagh Mavad Mokhadder', class = 'Mask', id = 'P.C. 7001', months = 0, fine = 0, color = 'green'},
        [8] = {title = 'Ghachaghe Ensan', class = 'Mask', id = 'P.C. 7001', months = 0, fine = 0, color = 'green'},

    },
    [8] = {
        [1] = {title = 'Criminal Possession of Weapon Class A', class = 'Felony', id = 'P.C. 8001', months = 10, fine = 500, color = 'green'},
        [2] = {title = 'Dashtan Gune Class 1', class = 'Felony', id = 'P.C. 8001', months = 15, fine = 1000, color = 'green'},
        [3] = {title = 'Dashtan Gune Class 2', class = 'Felony', id = 'P.C. 8001', months = 30, fine = 2000, color = 'green'},
        [4] = {title = 'Dashtan Gune Class 3', class = 'Felony', id = 'P.C. 8001', months = 60, fine = 3000, color = 'green'},
        [5] = {title = 'Dashtan Aslahe Dolati', class = 'Felony', id = 'P.C. 8001', months = 100, fine = 10000, color = 'green'},
        [6] = {title = 'Dashtan Mavad Monfajere ', class = 'Felony', id = 'P.C. 8001', months = 50, fine = 6000, color = 'green'},
        [7] = {title = 'Moghavemat Dar Barabare Afrade Dolati ', class = 'Felony', id = 'P.C. 8001', months = 10, fine = 500, color = 'green'},
        [8] = {title = 'Terrorism', class = 'Felony', id = 'P.C. 8001', months = 0, fine = 0, color = 'green'},
        [9] = {title = 'Ghachaghe Aslahe', class = 'Felony', id = 'P.C. 8001', months = 0, fine = 0, color = 'green'},
        [10] = {title = 'Dashtan Attachment Gun Ha', class = 'Felony', id = 'P.C. 8001', months = 40, fine = 5000, color = 'green'},
        [11] = {title = 'Foroosh Aslahe', class = 'Felony', id = 'P.C. 8001', months = 0, fine = 0, color = 'green'},


        
    },
    [9] = {
        [1] = {title = 'Driving While Intoxicated', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 300, color = 'green'},
        [2] = {title = 'Sorat Gheyre Mojaz Be Azaye Har 10 Km', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 100, color = 'green'},
        [3] = {title = 'Park Gheyre Mojaz', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 100, color = 'green'},
        [4] = {title = 'Ranandegi dar Halate Masti', class = 'Misdemeanor', id = 'P.C. 9001', months = 10, fine = 500, color = 'green'},
        [5] = {title = 'Farar Kardan As Police (Pursuit)', class = 'Misdemeanor', id = 'P.C. 9001', months = 15, fine = 300, color = 'green'},
        [6] = {title = 'Rananadegi Khatarnak', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 250, color = 'green'},
        [7] = {title = 'Ranandegi Bedoone Govahiname', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 0, color = 'green'},
        [8] = {title = 'Mosabeghe Khiabani', class = 'Misdemeanor', id = 'P.C. 9001', months = 20, fine = 1000, color = 'green'},
        
        
    },
    [10] = {
        [1] = {title = 'Hunting in Restricted Areas', class = 'Infraction', id = 'P.C. 10001', months = 0, fine = 450, color = 'green'},
        [2] = {title = 'Shenkare Gheyre Ghanooni', class = 'Infraction', id = 'P.C. 10001', months = 20, fine = 2000, color = 'green'},
        [3] = {title = 'Mahigiri Gheyre Ghanooni', class = 'Infraction', id = 'P.C. 10001', months = 15, fine = 2000, color = 'green'},
        
    }
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['sapr'] = true,
    ['pa'] = true -- yucky
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['judge'] = true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[5] = true,
        [6] = true,
        [7] = true,
	},
	['police'] = {
        [9] = true,
		[10] = true,
        [11] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'judge'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector4(459.1, -991.59, 25.7, 1.09), 
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}
