Products = {
    ["Mecanicoszinho"] = {
        [1] = {
            name = "hid_controller",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "underglow_controller",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "tint_supplies",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "wrappreto",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "wrapcinza",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "wrapvermelho",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "wraplaranja",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "wrapdourado",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "wrapamarelo",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "wrapverde",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "wrapblue",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "wrapbronze",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "wrapcastanho",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "wrapbranco",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "wraprosa",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "wraprosasalmao",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "wraproxo",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "matriculaamarelapreta",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "matriculaazulbranca2",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "matriculaamarelaazul",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "matriculaazulbranca",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "matriculaazulbranca3",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "maquinadiagonostico",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "repairkit",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "advancedrepairkit",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "cleaningkit",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "maquinadiagonostico",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "camerasmecanicos",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "airsuspension",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "coilovers",
            price = 125,
            amount = 1,
            info = {},
            type = "item",
            slot = 30,
        },
    },
}

Lojinha = {
    ["Mecanicoszinho"] = {
        ["label"] = "Shop Mechanics",
        ["type"] = "BM",
        ["coords"] = {
            [1] = {
                ["x"] = 1333.06,
                ["y"] = 4326.86,
                ["z"] = 38.017,
            },
        },
        ["CoisasBoas"] = Products["Mecanicoszinho"],
    },
}
