--to create blip (you can change coordinate, blip, name everything here)
Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(vector3(791.4, -758.72, 26.75))
    SetBlipSprite (Dealer, 628)
    SetBlipDisplay(Dealer, 4)
    SetBlipScale  (Dealer, 1.00)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 5)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName('Ítaliano Pizzeria')
    EndTextCommandSetBlipName(Dealer)
end)